/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.addpatient;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Zeinab
 */
public class patientinformation extends javax.swing.JFrame {

    /**
     * Creates new form patientinformation
     */
    public patientinformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        blood = new javax.swing.JTextField();
        birth = new javax.swing.JTextField();
        pnum = new javax.swing.JTextField();
        adrs = new javax.swing.JTextField();
        mr = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        close = new javax.swing.JButton();
        gen = new javax.swing.JComboBox<>();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        delid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Patient");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Patient ID :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Name :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Blood Type : ");

        g.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        g.setForeground(new java.awt.Color(0, 102, 102));
        g.setText("Gender :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Date Of Birth : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Phone Number : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Address : ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Medical Record : ");

        pid.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pid.setForeground(new java.awt.Color(0, 102, 102));

        n.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        n.setForeground(new java.awt.Color(0, 102, 102));
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        blood.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        blood.setForeground(new java.awt.Color(0, 102, 102));

        birth.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        birth.setForeground(new java.awt.Color(0, 102, 102));

        pnum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pnum.setForeground(new java.awt.Color(0, 102, 102));

        adrs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        adrs.setForeground(new java.awt.Color(0, 102, 102));

        mr.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mr.setForeground(new java.awt.Color(0, 102, 102));
        mr.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        add.setBackground(new java.awt.Color(0, 102, 102));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("View All Patients");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(0, 102, 102));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Add");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(0, 102, 102));
        close.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        gen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gen.setForeground(new java.awt.Color(0, 102, 102));
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        clear.setBackground(new java.awt.Color(0, 102, 102));
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 0, 0));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mr, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(255, 255, 255)
                                    .addComponent(jLabel13))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnum, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(blood, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(adrs, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(213, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(439, 439, 439))))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(46, 46, 46)
                        .addComponent(save)
                        .addGap(38, 38, 38)
                        .addComponent(clear)
                        .addGap(28, 28, 28)
                        .addComponent(close))
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delid))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g)
                            .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(mr, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(save)
                    .addComponent(close)
                    .addComponent(clear)
                    .addComponent(delete))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con;
    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
 this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      ArrayList<String>allPaitentInformation=new ArrayList();
        try {
            FileInputStream fs = new FileInputStream("PaitentInformation.txt");
            InputStreamReader ir=new InputStreamReader(fs);
         BufferedReader in = new BufferedReader(ir);
         
         while(in.ready())
        allPaitentInformation.add(in.readLine());
         
         in.close();
         
        } 
         catch (IOException ex) 
         { JOptionPane.showMessageDialog( null, "correct the file name ","message",JOptionPane.ERROR_MESSAGE);}
         int num=allPaitentInformation.size()/8;
         JFrame f=new JFrame();
         f.setSize(1000,300);
         JTable tab=new JTable(num,8);
         JScrollPane sc=new JScrollPane(tab);
         f.add(sc);
         f.setVisible(true);
         
         
          tab.getColumnModel().getColumn(0).setHeaderValue("Paitient ID");
         tab.getColumnModel().getColumn(1).setHeaderValue("Name ");
         tab.getColumnModel().getColumn(2).setHeaderValue("Blood Type  ");
         tab.getColumnModel().getColumn(3).setHeaderValue("Gender ");
         tab.getColumnModel().getColumn(4).setHeaderValue("Date Of Birth ");
         tab.getColumnModel().getColumn(5).setHeaderValue("Phone Number ");
           tab.getColumnModel().getColumn(6).setHeaderValue("Address ");
             tab.getColumnModel().getColumn(7).setHeaderValue("Medical Record ");
         
         int inf=0;
         int st=0;
         while (inf<allPaitentInformation.size()){
             tab.setValueAt(allPaitentInformation.get(inf), st,0);
         tab.setValueAt(allPaitentInformation.get(inf+1), st,1);
         tab.setValueAt(allPaitentInformation.get(inf+2), st,2);
         tab.setValueAt(allPaitentInformation.get(inf+3), st,3);
         tab.setValueAt(allPaitentInformation.get(inf+4), st,4);
         tab.setValueAt(allPaitentInformation.get(inf+5), st,5);
           tab.setValueAt(allPaitentInformation.get(inf+6), st,6);
             tab.setValueAt(allPaitentInformation.get(inf+7), st,7);
             
         inf+=8;
         st++;
         }
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
          
        PreparedStatement ps;

try {
Class.forName("com.mysql.cj.jdbc.Driver");
 con= DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
    System.out.println("connection is succesfull");


ps=con.prepareStatement("insert into patientinformation(patient_id,name,blood_type,gender,date_of_birth,phone_number,address,medical_record)values(?,?,?,?,?,?,?,?)");

ps.setInt(1,Integer.parseInt(pid.getText()));
ps.setString(2,n.getText());
ps.setString(3,blood.getText());
ps.setString(4,gen.getSelectedItem().toString());
ps.setString(5,birth.getText());
ps.setInt(6,Integer.parseInt(pnum.getText()));
ps.setString(7,adrs.getText());
ps.setString(8,mr.getText());
System.out.print(Integer.parseInt(pid.getText())+" "+n.getText()+" "+blood.getText()+" "+gen.getSelectedItem().toString()+" "+birth.getText()+" "+Integer.parseInt(pnum.getText())+" "+adrs.getText()+" "+mr.getText());
ps.executeUpdate();


Statement stmt = (Statement) con.createStatement();
}
catch (SQLException e) {

System.out.println("SQL Exception: "+e.toString());
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(patientinformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        try{
          FileWriter nf;
            
            nf=new  FileWriter("PaitentInformation.txt",true);
       nf.write(pid.getText()+"\n");
       nf.write(n.getText()+"\n");
       nf.write(blood.getText()+"\n");
       nf.write(gen.getSelectedItem().toString()+"\n");
       nf.write(birth.getText()+"\n");
       nf.write(pnum.getText()+"\n");
        nf.write(adrs.getText()+"\n");
         nf.write(mr.getText()+"\n");
       
       
       nf.close();
            
      } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       pid.setText("");
       n.setText("");
       blood.setText("");
       birth.setText("");
       pnum.setText("");
       adrs.setText("");
       mr.setText("");
       
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       PreparedStatement ps;

try {
Class.forName("com.mysql.cj.jdbc.Driver");
 con= DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
    System.out.println("connection is succesfull");


ps=con.prepareStatement("DELETE FROM `patientinformation` WHERE patient_id=?");
System.out.print(delid.getText());
ps.setInt(1,Integer.parseInt(delid.getText().trim()));

//ps.setString(1,n.getText());
//psng(3,blood.getText());
//ps.setString(4,gen.getSelectedItem().toString());
//ps.setString(5,birth.getText());
//ps.setInt(6,Integer.parseInt(pnum.getText()));
//ps.setString(7,adrs.getText());
//ps.setString(8,mr.getText());
//System.out.print(Integer.parseInt(pid.getText())+" "+n.getText()+" "+blood.getText()+" "+gen.getSelectedItem().toString()+" "+birth.getText()+" "+Integer.parseInt(pnum.getText())+" "+adrs.getText()+" "+mr.getText());
ps.executeUpdate();


Statement stmt = (Statement) con.createStatement();
}
catch (SQLException e) {

System.out.println("SQL Exception: "+e.toString());
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(patientinformation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientinformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField adrs;
    private javax.swing.JTextField birth;
    private javax.swing.JTextField blood;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JTextField delid;
    private javax.swing.JLabel g;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mr;
    private javax.swing.JTextField n;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pnum;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
